// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoX1f-QA0mL98PB9-ZXyy2couClv_aPdw',
    appId: '1:627387610740:web:17c541da1625ead7abc321',
    messagingSenderId: '627387610740',
    projectId: 'verificacion-886d7',
    authDomain: 'verificacion-886d7.firebaseapp.com',
    storageBucket: 'verificacion-886d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwF8xzFLhK9SbxNQWgAmHSYPJm18WHec',
    appId: '1:627387610740:android:9ebe15c26f637916abc321',
    messagingSenderId: '627387610740',
    projectId: 'verificacion-886d7',
    storageBucket: 'verificacion-886d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNUkOF24qWEHWtXlQdC7PHnMvdsyrivA',
    appId: '1:627387610740:ios:cd2b338d11a4fe9cabc321',
    messagingSenderId: '627387610740',
    projectId: 'verificacion-886d7',
    storageBucket: 'verificacion-886d7.appspot.com',
    iosBundleId: 'com.example.contador',
  );
}
